name: Auto-Release

on: 
  push:
    branches: 
    - 'main'
  workflow_dispatch:
    inputs:
      version:
        description: Version Override
        required: false
        type: string
  schedule:
  - cron: 37 1/3 * * *

jobs:
  check-for-resonite-update:
    runs-on: ubuntu-slim
    outputs:
      UP_TO_DATE: ${{ steps.check-version.outputs.UP_TO_DATE }}
    steps:
    - name: Query Resonite version and check if matching tag exists
      id: check-version
      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Checking for current Resonite version..."
        RESONITE_VERSION=$( curl -s https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/ResoniteAssemblies/refs/heads/main/Assemblies/RESONITE_VERSION | tr -d '\r\n ' ) || exit 1
        if [ -z "$RESONITE_VERSION" ]
        then
          echo "Invalid Resonite version '$RESONITE_VERSION'!" >&2
          exit 2
        fi
        echo "Searching for release tags built with Resonite $RESONITE_VERSION..."
        MATCHING_RELEASES=$( git ls-remote --tags ${{github.repositoryUrl}} "*-$RESONITE_VERSION" ) || exit 3
        if printf %s "$MATCHING_RELEASES" | grep -Fq "-$RESONITE_VERSION"
        then
          printf "Found:\n%s\n" "$MATCHING_RELEASES"
          echo "Cancelling release workflow..."
          echo "UP_TO_DATE=true" >> "$GITHUB_OUTPUT"
        else
          echo "No matching releases found!"
          echo "Continuing with release workflow..."
        fi
  release:
    runs-on: ubuntu-latest
    needs:
      check-for-resonite-update
    if: ${{ needs.check-for-resonite-update.UP_TO_DATE != 'true' }}
    permissions:
      contents: write
    steps:
    - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 #v6.0.0
      with:
        dotnet-version: '10'
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: Build
      id: build
      run: |
        ./build.sh || exit $?
        dotnet tool restore || exit $?
        echo "resonite_version=$(dotnet script get-assembly-version.csx ResoniteAssemblies/FrooxEngine.dll)" >> "$GITHUB_OUTPUT" || exit $?
        echo "mod_version=$(dotnet script get-assembly-version.csx ResoniteAssemblies/rml_mods/*.dll)" >> "$GITHUB_OUTPUT" || exit $?
    - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.12.0
      with:
        tag: "v${{ inputs.version || steps.build.outputs.mod_version }}-${{steps.build.outputs.resonite_version}}"
        artifacts: "ResoniteAssemblies/rml_mods/*.dll" #Use this if your mod runs with a single dll file!
#       artifacts: "ResoniteAssemblies/*.zip" #Use this if you need to include libraries or other assets!
        makeLatest: true
        body: |
          TODO