name: Check for Resonite Updates

on:
  workflow_dispatch:
  schedule:
  - cron: 37 1/3 * * *

jobs:
  check-for-resonite-update:
    runs-on: ubuntu-slim
    outputs:
      UP_TO_DATE: ${{steps.check-version.outputs.UP_TO_DATE}}
      RESONITE_VERSION: ${{steps.check-version.outputs.RESONITE_VERSION}}
    steps:
    - name: Query Resonite version and check if matching tag exists
      id: check-version
      run: | #This is not put in an sh file because doing so would require downloading the repository.
        echo "Checking for current Resonite version..."
        SAFE_VERSION_PATTERN='^[\w\.]+$' #SECURITY: prevents interpretation when written into $GITHUB_OUTPUT
        RESONITE_VERSION="$( curl -s https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/ResoniteAssemblies/refs/heads/main/Assemblies/RESONITE_VERSION | head -n 1 | tr -d '\r\n ' )" || exit 1
        if [[ ! "$RESONITE_VERSION" =~ $SAFE_VERSION_PATTERN ]]
        then
          echo "Invalid Resonite version '$RESONITE_VERSION'!" >&2
          exit 2
        fi

        echo "Searching for release tags built with Resonite $RESONITE_VERSION..."
        MATCHING_RELEASES="$( git ls-remote --tags 'https://github.com/${{github.repository}}' "*-$RESONITE_VERSION" )" || exit 3
        if printf %s "$MATCHING_RELEASES" | grep -Fq -- "-$RESONITE_VERSION"
        then
          printf "Found:\n%s\n" "$MATCHING_RELEASES"
          echo "Cancelling release workflow..."
          echo "UP_TO_DATE=true" >> "$GITHUB_OUTPUT"
        else
          echo "No matching releases found!"
          echo "Continuing with release workflow..."
          echo "RESONITE_VERSION=$RESONITE_VERSION" >> "$GITHUB_OUTPUT"
        fi
  trigger-release:
    if: jobs.check-for-resonite-update.outputs.UP_TO_DATE != 'true'
    uses: $/.github/workflows/build-release.yml
    with:
      description: "Automatic rebuild with Resonite ${{jobs.check-for-resonite-update.outputs.RESONITE_VERSION}}"
