name: Prepare RML Manifest

on:
  workflow_dispatch:

jobs:
  release:  
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
    - name: Fail if missing requirements
      if: ${{secrets.RML_MANIFEST_TOKEN}} == ''
      run: |
        echo "Expected secret RML_MANIFEST_TOKEN to push to repository $GITHUB_REPOSITORY_OWNER}}/resonite-mod-manifest"
        exit 1
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        repository: ${{github.repository_owner}}/resonite-mod-manifest
        token: ${{secrets.RML_MANIFEST_TOKEN}}
    - name: Update and push manifest
      run: |
        #TODO: download script
        ./prepare-rml-manifest.yml TODO
        git add TODO
        git commit -m 'TODO'
        git push
      